CREATE TABLE BI_OLAP_4.DM_FactSales
(
  SalesOrderID     INT AUTO_INCREMENT,
  RevisionNumber   INT          NOT NULL,
  OrderDate        DATE     NOT NULL,
  DueDate          DATE     NOT NULL,
  ShipDate         DATE,
  Status           INT          NOT NULL CHECK (Status >= 1 & Status <= 6),
  SalesOrderNumber VARCHAR(200) NOT NULL UNIQUE,
  CustomerID       INT          NOT NULL,
  ShipToAddressID  INT          NOT NULL,
  BillToAddressID  INT          NOT NULL,
  ShipMethodID     INT          NOT NULL,
  OrderQty           INT            NOT NULL,
  ProductID          INT            NOT NULL,
  UnitPrice          NUMERIC(12, 2) NOT NULL,
  CONSTRAINT FK_Customer2 FOREIGN KEY (CustomerID) REFERENCES DM_Customer (CustomerID),
  CONSTRAINT FK_ShipToAddress FOREIGN KEY (ShipToAddressID) REFERENCES DM_Location (AddressID),
  CONSTRAINT FK_BillToAddress FOREIGN KEY (BillToAddressID) REFERENCES DM_Location (AddressID),
  CONSTRAINT FK_OrderDate FOREIGN KEY (OrderDate) REFERENCES DM_Time (Date),
  CONSTRAINT FK_DueDate FOREIGN KEY (DueDate) REFERENCES DM_Time (Date),
  CONSTRAINT FK_ShipDate FOREIGN KEY (ShipDate) REFERENCES DM_Time (Date),
  FOREIGN KEY FK_Product (ProductID) REFERENCES DM_Product (ProductID),
  PRIMARY KEY PK_FactSales (SalesOrderID, SalesOrderNumber)
);
