CREATE TABLE BI_OLAP_4.DM_FactSales
(
  SalesOrderNumber VARCHAR(200) NOT NULL,
  SalesOrderLineNumber VARCHAR(100) NOT NULL,
  CustomerID       INT          NOT NULL,
  ProductID				INT NOT NULL,
  ShipToAddressID  INT          NOT NULL,
  BillToAddressID  INT          NOT NULL,
  ShipmentMethod     VARCHAR(200)          NOT NULL,
  UnitPrice          NUMERIC(12, 2) NOT NULL,
  Discount					 NUMERIC(10,4)	NOT NULL,
  OrderQty           INT            NOT NULL,
  OrderLineTotal		NUMERIC(10,4) NOT NULL,
  OrderLineProfit		NUMERIC(10,4) NOT NULL,
  TaxAmount		NUMERIC(10,4) NOT NULL,
  OrderLineFreightCost		NUMERIC(10,4) NOT NULL,
  OrderStatus INT,
  OrderDate Date,
  DueDate Date,
  ShipDate Date,
  IsLateShipment INTEGER,

  CONSTRAINT FK_Customer FOREIGN KEY (CustomerID) REFERENCES DM_Customer (CustomerID),
  CONSTRAINT FK_Product FOREIGN KEY (ProductID) REFERENCES DM_Product (ProductID),
  CONSTRAINT FK_ShipToAddress FOREIGN KEY (ShipToAddressID) REFERENCES DM_Location (AddressID),
  CONSTRAINT FK_BillToAddress FOREIGN KEY (BillToAddressID) REFERENCES DM_Location (AddressID),
  CONSTRAINT FK_OrderDate FOREIGN KEY (OrderDate) REFERENCES DM_Time (Date),
  CONSTRAINT FK_DueDate FOREIGN KEY (DueDate) REFERENCES DM_Time (Date),
  CONSTRAINT FK_ShipDate FOREIGN KEY (ShipDate) REFERENCES DM_Time (Date),
  PRIMARY KEY PK_FactSales (SalesOrderNumber, SalesOrderLineNumber)
);
