CREATE TABLE movies
(movieID BIGINT,
title STRING,
genres ARRAY<STRING>)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ','
  COLLECTION ITEMS TERMINATED BY '|'
STORED AS TEXTFILE;

CREATE TABLE tags
(userId BIGINT,
 movieId BIGINT,
 tag STRING,
 timestamp BIGINT)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE ratings
(userId BIGINT,
 movieId BIGINT,
 rating DECIMAL,
 timestamp BIGINT)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE genome_scores
(movieId BIGINT,
 tagId BIGINT,
 relevance DOUBLE)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE genome_tags
(tagId BIGINT,
 tag STRING)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

